#-----------------------------------------------------------------------------------
# System tests covering interlocking, automation and approach control functions
#
# When run as 'main' it uses the following example schematic files:
#     "../configuration_examples/automation_colour_light_example.sig"
#     "../configuration_examples/automation_semaphore_example.sig"
#
# Re-uses the interlocking and route setting system tests from test_interlocking_examples.py
#-----------------------------------------------------------------------------------

from system_test_harness import *
import test_interlocking_examples
import test_object_edit_windows

#-----------------------------------------------------------------------------------

def run_initial_state_tests(semaphore=False):
    print("Initial state tests")
    assert_signals_route_MAIN(1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19)
    assert_signals_route_LH1(2)
    assert_signals_DANGER(1,2,3,4,5,6,7,8,12,13,14,15)
    assert_signals_CAUTION(9,16)
    assert_signals_PROCEED(10,11,18,19)
    assert_points_unlocked(2,3,5)
    assert_signals_unlocked(1,3,4,5,6,7,8,12,13,15)
    assert_subsidaries_unlocked(1,2,3)
    assert_signals_locked(2,14)
    assert_sections_clear(1,2,3,4,5,6,7,8,9,10,11,12,13)
    assert_signals_override_clear(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19)
    assert_signals_app_cntl_clear(17,16,2,4,9,12,10,18,19,11)
    if semaphore:
        assert_signals_PROCEED(17)
        assert_signals_override_caution_set(9,116)
        assert_signals_app_cntl_set(1,3,8)
    else:
        assert_signals_PRELIM_CAUTION(17)
        assert_signals_app_cntl_clear(1)
    return()

#-----------------------------------------------------------------------------------

def run_colour_light_aspect_tests():
    print("Colour Light Aspect tests")
    # Test the default state
    assert_signals_PROCEED(11,19,18,10)
    assert_signals_DANGER(8,1,2,3,4,12)
    assert_signals_CAUTION(16,9)
    assert_signals_PRELIM_CAUTION(17)
    # Main Route 1
    set_signals_off(8,1,3,4)
    assert_signals_PROCEED(17,16,8,1,3,4)
    set_signals_on(4)
    assert_signals_CAUTION(3)
    assert_signals_PRELIM_CAUTION(1)
    assert_signals_PROCEED(8,16,17)
    set_signals_on(3)
    assert_signals_CAUTION(1)
    assert_signals_PRELIM_CAUTION(8)
    assert_signals_PROCEED(16,17)
    set_signals_on(1)
    assert_signals_CAUTION(8)
    assert_signals_PRELIM_CAUTION(16)
    assert_signals_PROCEED(17)
    set_signals_on(8)
    assert_signals_CAUTION(16)
    assert_signals_PRELIM_CAUTION(17)
    # Main Route Loop
    set_fpls_off(2,3)
    set_points_switched(2,3)
    set_fpls_on(2,3)
    set_signals_off(8,1,2,4)
    assert_signals_PROCEED(2,4)
    assert_signals_CAUTION_APP_CNTL(1)
    assert_signals_FLASH_CAUTION(8)
    assert_signals_FLASH_PRELIM_CAUTION(16)
    assert_signals_PROCEED(17)
    set_signals_on(4)
    assert_signals_DANGER(4)
    assert_signals_CAUTION(2)
    assert_signals_CAUTION_APP_CNTL(1)
    assert_signals_FLASH_CAUTION(8)
    assert_signals_FLASH_PRELIM_CAUTION(16)
    assert_signals_PROCEED(17)
    set_signals_on(2)
    assert_signals_DANGER(2)
    assert_signals_CAUTION_APP_CNTL(1)
    assert_signals_FLASH_CAUTION(8)
    assert_signals_FLASH_PRELIM_CAUTION(16)
    assert_signals_PROCEED(17)
    set_signals_on(1)
    assert_signals_DANGER(1)
    assert_signals_CAUTION(8)
    assert_signals_PRELIM_CAUTION(16)
    assert_signals_PROCEED(17)
    set_signals_on(8)
    assert_signals_DANGER(8)
    assert_signals_CAUTION(16)
    assert_signals_PRELIM_CAUTION(17)
    # Test 'signal released' aspects
    set_signals_off(8,1,2,4)
    assert_signals_PROCEED(2,4)
    assert_signals_CAUTION_APP_CNTL(1)
    assert_signals_FLASH_CAUTION(8)
    assert_signals_FLASH_PRELIM_CAUTION(16)
    assert_signals_PROCEED(17)
    trigger_signals_released(1)
    assert_signals_PROCEED(17,16,8,1)
    set_signals_on(8,1,2,4)
    # Switch points back to main line
    set_fpls_off(2,3)
    set_points_normal(2,3)
    set_fpls_on(2,3)
    # Main Route 2
    assert_signals_DANGER(12)
    assert_signals_CAUTION(9)
    assert_signals_PROCEED(11,19,18,10)
    set_signals_off(12)
    assert_signals_PROCEED(12,9)
    set_signals_on(12)
    # Test everything has been returned to the default state
    assert_signals_PROCEED(11,19,18,10)
    assert_signals_DANGER(8,1,2,3,4,12)
    assert_signals_CAUTION(16,9)
    assert_signals_PRELIM_CAUTION(17)
    return()

#-----------------------------------------------------------------------------------

def run_semaphore_aspect_tests():
    print("Semaphore Aspect tests")
    # Test the default state
    assert_signals_PROCEED(17,10,18,19,11)
    assert_signals_DANGER(8,1,2,3,4,12)
    assert_signals_CAUTION(16,9)
    # Main Route 1
    set_signals_off(8,1,3,4)
    assert_signals_PROCEED(8,1,3,4,16,17)
    set_signals_on(4)
    assert_signals_DANGER(8,1,3,4)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # test approach control aspects
    trigger_signals_released(3)
    assert_signals_PROCEED(3)
    # Set signal to on (set it back to DANGER)
    set_signals_on(3)
    assert_signals_DANGER(8,1,3)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # test approach control aspects
    trigger_signals_released(1)
    assert_signals_PROCEED(1)
    # Set signal to on (set it back to DANGER)
    set_signals_on(1)
    assert_signals_DANGER(8,1)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # test approach control aspects
    trigger_signals_released(8)
    assert_signals_PROCEED(8)
    # Set signal to on (set it back to DANGER)
    set_signals_on(8)
    assert_signals_DANGER(8)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # Main Route Loop
    # Note signal 1 is subject to approach control for LH1
    set_fpls_off(2,3)
    set_points_switched(2,3)
    set_fpls_on(2,3)
    set_signals_off(8,1,2,4)
    assert_signals_PROCEED(2,4,17)
    assert_signals_CAUTION(16)
    assert_signals_DANGER(8,1)
    set_signals_on(4)
    assert_signals_DANGER(8,1,2,4)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # test approach control aspects
    trigger_signals_released(2)
    assert_signals_PROCEED(2)
    # Set signal to on (set it back to DANGER)
    set_signals_on(2)
    assert_signals_DANGER(8,1,2)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # test approach control aspects
    trigger_signals_released(1)
    assert_signals_PROCEED(1)
    # Set signal to on (set it back to DANGER)
    set_signals_on(1)
    assert_signals_DANGER(8,1)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # test approach control aspects
    trigger_signals_released(8)
    assert_signals_PROCEED(8)
    # Set signal to on (set it back to DANGER)
    set_signals_on(8)
    assert_signals_DANGER(8)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    # Switch points back to main line
    set_fpls_off(2,3)
    set_points_normal(2,3)
    set_fpls_on(2,3)
    # Main Route 2
    assert_signals_DANGER(12)
    assert_signals_CAUTION(9)
    assert_signals_PROCEED(11,19,18,10)
    set_signals_off(12)
    assert_signals_PROCEED(11,19,18,10,12,9)
    set_signals_on(12)
    # Test everything has been returned to the default state
    assert_signals_PROCEED(17,10,18,19,11)
    assert_signals_DANGER(8,1,2,3,4,12)
    assert_signals_CAUTION(16,9)
    return()

#-----------------------------------------------------------------------------------

def run_signal_override_tests():
    print("Signal Override Tests")
    # test the default state
    assert_signals_override_clear(1,2,3,4,8,9,10,12,16,17,18,19)
    # Signal 17
    assert_signals_override_clear(17)
    set_sections_occupied(5)
    assert_signals_override_set(17)
    set_sections_clear(5)
    assert_signals_override_clear(17)
    # Signal 16
    assert_signals_override_clear(16)
    set_sections_occupied(1)
    assert_signals_override_set(16)
    set_sections_clear(1)
    assert_signals_override_clear(16)
    # Signal 8
    assert_signals_override_clear(8)
    set_sections_occupied(2)
    assert_signals_override_set(8)
    set_sections_clear(2)
    assert_signals_override_clear(8)
    # Signal 1 - main route
    assert_signals_override_clear(1)
    set_sections_occupied(3)
    assert_signals_override_set(1)
    set_sections_clear(3)
    assert_signals_override_clear(1)
    set_fpls_off(2)
    set_points_switched(2)
    set_fpls_on(2)
    assert_signals_override_clear(1)
    set_sections_occupied(12)
    assert_signals_override_set(1)
    set_sections_clear(12)
    assert_signals_override_clear(1)
    set_fpls_off(2)
    set_points_normal(2)
    set_fpls_on(2)
    # Signal 3
    assert_signals_override_clear(3)
    set_sections_occupied(4)
    assert_signals_override_set(3)
    set_sections_clear(4)
    assert_signals_override_clear(3)
    # Signal 2
    set_fpls_off(3)
    set_points_switched(3)
    set_fpls_on(3)
    assert_signals_override_clear(2)
    set_sections_occupied(4)
    assert_signals_override_set(2)
    set_sections_clear(4)
    assert_signals_override_clear(2)
    set_fpls_off(3)
    set_points_normal(3)
    set_fpls_on(3)
    # Signal 9 (Semaphore Signal 9 is overridden on home signals ahead)
    set_sections_occupied(7)
    assert_signals_override_set(9)
    set_sections_clear(7)
    # Signal 12
    assert_signals_override_clear(12)
    set_sections_occupied(8)
    assert_signals_override_set(12)
    set_sections_clear(8)
    assert_signals_override_clear(12)
    # Signal 10
    set_sections_occupied(9)
    assert_signals_override_set(10)
    set_sections_clear(9)
    assert_signals_override_clear(10)
    # Signal 18 (Semaphore Signal 18 is overridden on home signals ahead)
    # But signals 11 and 19 are automatic so Signal 18 override will be clear)
    set_sections_occupied(14)
    assert_signals_override_set(18)
    set_sections_clear(14)
    assert_signals_override_clear(18)
    # Signal 19
    assert_signals_override_clear(19)
    set_sections_occupied(15)
    assert_signals_override_set(19)
    set_sections_clear(15)
    assert_signals_override_clear(19)
    # test everything has been set back to the default state
    assert_signals_override_clear(1,2,3,4,8,9,10,12,16,17,18,19)
    return()

#-----------------------------------------------------------------------------------

def run_semaphore_override_ahead_tests():
    print("Semaphore override ahead Tests")
    # test the default state
    assert_signals_override_caution_set(9,116)
    # bottom main line
    set_signals_off(12)
    assert_signals_override_caution_clear(9)
    set_signals_on(12)
    # top main line - route 1
    set_signals_off(8)
    assert_signals_override_caution_set(116)
    set_signals_off(1)
    assert_signals_override_caution_set(116)
    set_signals_off(3)
    assert_signals_override_caution_set(116)
    set_signals_off(4)
    assert_signals_override_caution_clear(116)
    set_signals_on(8)
    assert_signals_override_caution_set(116)
    set_signals_on(1)
    assert_signals_override_caution_set(116)
    set_signals_on(3)
    assert_signals_override_caution_set(116)
    set_signals_on(4)
    assert_signals_override_caution_set(116)
    # top main line - loop
    set_fpls_off(2,3)
    set_points_switched(2,3)
    set_fpls_on(2,3)
    set_signals_off(8)
    assert_signals_override_caution_set(116)
    set_signals_off(1)
    assert_signals_override_caution_set(116)
    set_signals_off(2)
    assert_signals_override_caution_set(116)
    set_signals_off(4)
    assert_signals_override_caution_set(116)
    # Now release signal 1 approach control
    trigger_signals_released(1)
    assert_signals_override_caution_clear(116)
    set_signals_on(8)
    assert_signals_override_caution_set(116)
    set_signals_on(1)
    assert_signals_override_caution_set(116)
    set_signals_on(2)
    assert_signals_override_caution_set(116)
    set_signals_on(4)
    assert_signals_override_caution_set(116)
    set_fpls_off(2,3)
    set_points_normal(2,3)
    set_fpls_on(2,3)
    # test everything has returned to the default state
    assert_signals_override_caution_set(9,116)
    return()

#-----------------------------------------------------------------------------------

def run_main_line_tests_1(delay=0):
    print("Main line tests 1")
    # This clears all the signals and sends a train from Left to right along the main line
    sleep(delay)
    set_signals_off(8,1,3,4)
    set_sections_occupied(10)
    sleep(delay)
    trigger_signals_passed(17)
    assert_sections_occupied(5)
    assert_sections_clear(10)
    sleep(delay)
    trigger_signals_passed(16)
    assert_sections_occupied(1)
    assert_sections_clear(5)
    sleep(delay)
    trigger_signals_passed(8)
    assert_sections_occupied(2)
    assert_sections_clear(1)
    sleep(delay/2)
    trigger_signals_released(1)
    sleep(delay/2)
    trigger_signals_passed(1)
    assert_sections_occupied(3)
    assert_sections_clear(2)
    sleep(delay/2)
    trigger_signals_passed(15)
    sleep(delay/2)
    trigger_signals_passed(3)
    assert_sections_occupied(4)
    assert_sections_clear(3)
    sleep(delay/2)
    trigger_signals_passed(13)
    sleep(delay/2)
    trigger_signals_passed(4)
    assert_sections_clear(4)
    # Wait for the timed signal sequences to finish
    sleep(5.0)
    # Revert the signals to danger
    set_signals_on(8,1,3,4)
    return()

#-----------------------------------------------------------------------------------

def run_main_line_tests_2(delay=0):
    print("Main line tests 2")
    # This clears all the signals and sends a train from right to left along the main line
    sleep(delay)
    set_signals_off(12)
    set_sections_occupied(6)
    sleep(delay)
    trigger_signals_passed(9)
    assert_sections_occupied(7)
    assert_sections_clear(6)
    sleep(delay)
    trigger_signals_passed(12)
    assert_sections_occupied(8)
    assert_sections_clear(7)
    sleep(delay/2)
    trigger_signals_passed(14)
    sleep(delay/2)
    trigger_signals_passed(10)
    assert_sections_occupied(9)
    assert_sections_clear(8)
    sleep(delay)
    trigger_signals_passed(18)
    assert_sections_occupied(14)
    assert_sections_clear(15)
    sleep(delay)
    trigger_signals_passed(19)
    assert_sections_occupied(15)
    assert_sections_clear(14)
    sleep(delay)
    trigger_signals_passed(11)
    assert_sections_clear(15)
    # Wait for the timed signal sequences to finish
    sleep(5.0)
    # revert the signal to danger
    set_signals_on(12)
    return()

#-----------------------------------------------------------------------------------

def run_loop_line_tests(delay=0):
    print("Loop line tests")
    # This clears all the signals and sends a train from right to left via the loop line
    # Note the loop line is subject to approach control (controlled via signal 1)
    sleep(delay)
    # Change point 1 3 for the new route
    set_fpls_off(2,3)
    set_points_switched(2,3)
    set_fpls_on(2,3)
    # Clear the signals for the loop line
    sleep(delay)
    set_signals_off(8,1,2,4)
    # Now feed in the first train
    sleep(delay)
    set_sections_occupied(10)
    sleep(delay)
    trigger_signals_passed(17)
    assert_sections_occupied(5)
    assert_sections_clear(10)
    sleep(delay)
    trigger_signals_passed(16)
    assert_sections_occupied(1)
    assert_sections_clear(5)
    sleep(delay)
    trigger_signals_released(8)
    sleep(delay)
    trigger_signals_passed(8)
    assert_sections_occupied(2)
    assert_sections_clear(1)
    sleep(delay/2)
    assert_signals_app_cntl_set(1)
    trigger_signals_released(1)
    assert_signals_app_cntl_clear(1)
    sleep(delay/2)
    trigger_signals_passed(1)
    assert_signals_app_cntl_set(1)
    assert_sections_occupied(12)
    assert_sections_clear(2)
    sleep(delay/2)
    trigger_signals_passed(6)
    sleep(delay/2)
    trigger_signals_passed(2)
    assert_sections_occupied(4)
    assert_sections_clear(12)
    sleep(delay/2)
    trigger_signals_passed(13)
    sleep(delay/2)
    trigger_signals_passed(4)
    assert_sections_clear(4)
    # Wait for the timed signal sequences to finish
    sleep(5.0)
    # Revert the signals to danger
    set_signals_on(8,1,2,4)
    # Revert the points
    sleep(delay)
    set_fpls_off(2,3)
    set_points_normal(2,3)
    set_fpls_on(2,3)
    return()

#-----------------------------------------------------------------------------------

def run_main_line_approach_control_tests(delay=0):
    print("Main line approach control tests")
    # This clears all the signals apart from the last Home signal and sends a train from
    # Left to right along the main line, using approach control to clear each signal
    sleep(delay)
    set_signals_off(8,1,3)
    assert_signals_app_cntl_set(8,1,3)
    assert_signals_DANGER(8,1,3,4)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    set_sections_occupied(10)
    sleep(delay)
    trigger_signals_passed(17)
    sleep(delay)
    trigger_signals_passed(16)
    sleep(delay/2)
    trigger_signals_released(8)
    assert_signals_app_cntl_clear(8)
    assert_signals_PROCEED(8)
    sleep(delay/2)
    trigger_signals_passed(8)
    assert_signals_app_cntl_set(8)
    assert_signals_DANGER(8)
    sleep(delay/2)
    trigger_signals_released(1)
    assert_signals_app_cntl_clear(1)
    assert_signals_PROCEED(1)
    sleep(delay/2)
    trigger_signals_passed(1)
    assert_signals_app_cntl_set(1)
    assert_signals_DANGER(1)
    sleep(delay/2)
    trigger_signals_released(3)
    assert_signals_app_cntl_clear(3)
    assert_signals_PROCEED(3)
    sleep(delay/2)
    trigger_signals_passed(3)
    assert_signals_app_cntl_set(3)
    assert_signals_DANGER(3)
    sleep(delay/2)
    set_signals_off(4)
    trigger_signals_passed(4)
    # Wait for the timed signal sequences to finish
    sleep(5.0)
    # Revert the signals to danger
    set_signals_on(8,1,3,4)
    return()

#-----------------------------------------------------------------------------------

def run_loop_line_approach_control_tests(delay=0):
    print("Loop line approach control tests")
    # This clears all the signals apart from the last Home signal and sends a train from
    # Left to right along the loop line, using approach control to clear each signal
    sleep(delay)
    # Change points 2 3 for the new route
    set_fpls_off(2,3)
    set_points_switched(2,3)
    set_fpls_on(2,3)
    sleep(delay)
    set_signals_off(8,1,2)
    assert_signals_app_cntl_set(8,1,2)
    assert_signals_DANGER(8,1,2,4)
    assert_signals_CAUTION(16)
    assert_signals_PROCEED(17)
    set_sections_occupied(10)
    sleep(delay)
    trigger_signals_passed(17)
    sleep(delay)
    trigger_signals_passed(16)
    sleep(delay/2)
    trigger_signals_released(8)
    assert_signals_app_cntl_clear(8)
    assert_signals_PROCEED(8)
    sleep(delay/2)
    trigger_signals_passed(8)
    assert_signals_app_cntl_set(8)
    assert_signals_DANGER(8)
    sleep(delay/2)
    trigger_signals_released(1)
    assert_signals_app_cntl_clear(1)
    assert_signals_PROCEED(1)
    sleep(delay/2)
    trigger_signals_passed(1)
    assert_signals_app_cntl_set(1)
    assert_signals_DANGER(1)
    sleep(delay/2)
    trigger_signals_released(2)
    assert_signals_app_cntl_clear(2)
    assert_signals_PROCEED(2)
    sleep(delay/2)
    trigger_signals_passed(2)
    assert_signals_app_cntl_set(2)
    assert_signals_DANGER(2)
    sleep(delay/2)
    set_signals_off(4)
    trigger_signals_passed(4)
    # Wait for the timed signal sequences to finish
    sleep(5.0)
    # Revert the signals to danger
    set_signals_on(8,1,2,4)
    # Revert the points
    sleep(delay)
    set_fpls_off(2,3)
    set_points_normal(2,3)
    set_fpls_on(2,3)
    return()

#-----------------------------------------------------------------------------------

def run_shunting_tests(delay=0):
    print("Shunting tests")
    set_sections_occupied(4)
    sleep(delay)
    # Test the crossover first
    set_points_switched(5)
    sleep(delay)
    set_signals_off(13)
    sleep(delay)
    trigger_signals_passed(13)
    assert_sections_occupied(8)
    assert_sections_clear(4)
    sleep(delay/2)
    trigger_signals_passed(14)
    sleep(delay)
    # Now go back the other way
    set_signals_on(13)
    set_signals_off(14)
    sleep(delay)
    trigger_signals_passed(14)
    assert_sections_occupied(4)
    assert_sections_clear(8)
    sleep(delay/2)
    trigger_signals_passed(13)
    sleep(delay/2)
    set_signals_on(14)
    # Revert the points
    set_points_normal(5)
    sleep(delay)
    # Now reverse down the main line
    set_signals_off(13,15)
    sleep(delay)
    trigger_signals_passed(13)
    assert_sections_occupied(3)
    assert_sections_clear(4)
    sleep(delay/2)
    trigger_signals_passed(3)
    sleep(delay/2)
    trigger_signals_passed(15)
    assert_sections_occupied(2)
    assert_sections_clear(3)
    sleep(delay/2)
    trigger_signals_passed(1)
    sleep(delay)
    set_signals_on(13,15)
    # Move into the loop RH siding
    sleep(delay)
    set_fpls_off(2)
    set_points_switched(2)
    set_fpls_on(2)
    sleep(delay)
    set_subsidaries_off(1,2)
    sleep(delay)
    trigger_signals_passed(1)
    assert_sections_occupied(12)
    assert_sections_clear(2)
    sleep(delay/2)
    trigger_signals_passed(6)
    sleep(delay/2)
    trigger_signals_passed(2)
    assert_sections_occupied(13)
    assert_sections_clear(12)
    sleep(delay/2)
    trigger_signals_passed(7)
    sleep(delay)
    set_subsidaries_on(1,2)
    sleep(delay)
    # Set the route for the LH siding
    set_fpls_off(2)
    set_points_normal(2)
    set_fpls_on(2)
    sleep(delay)
    set_signals_off(7,6)
    sleep(delay)
    trigger_signals_passed(7)
    assert_sections_occupied(12)
    assert_sections_clear(13)
    sleep(delay/2)
    trigger_signals_passed(2)
    sleep(delay/2)
    trigger_signals_passed(6)
    assert_sections_occupied(11)
    assert_sections_clear(12)
    sleep(delay/2)
    trigger_signals_passed(5)
    sleep(delay)
    set_signals_on(7,6)
    # Now move out of the siding back onto the loop
    sleep(delay)
    set_signals_off(5)
    sleep(delay)
    trigger_signals_passed(5)
    assert_sections_occupied(12)
    assert_sections_clear(11)
    sleep(delay/2)
    trigger_signals_passed(6)
    sleep(delay)
    set_signals_on(5)
    sleep(delay)
    # Reverse back onto the main line
    set_fpls_off(2)
    set_points_switched(2)
    set_fpls_on(2)
    sleep(delay)
    set_signals_off(6)
    sleep(delay)
    trigger_signals_passed(6)
    assert_sections_occupied(2)
    assert_sections_clear(12)
    sleep(delay/2)
    trigger_signals_passed(1)
    sleep(delay)
    set_signals_on(6)
    sleep(delay)
    set_fpls_off(2)
    set_points_normal(2)
    set_fpls_on(2)
    sleep(delay)
    # Now go forwards on the main line
    set_subsidaries_off(1,3)
    sleep(delay)
    trigger_signals_passed(1)
    assert_sections_occupied(3)
    assert_sections_clear(2)
    sleep(delay/2)
    trigger_signals_passed(15)
    sleep(delay/2)
    trigger_signals_passed(3)
    assert_sections_occupied(4)
    assert_sections_clear(3)
    sleep(delay/2)
    trigger_signals_passed(13)
    sleep(delay)
    set_subsidaries_on(1,3)
    sleep(delay)
    # Reverse back into the loop
    set_fpls_off(3)
    set_points_switched(3)
    set_fpls_on(3)
    sleep(delay)
    set_signals_off(13)
    sleep(delay)
    trigger_signals_passed(13)
    assert_sections_occupied(12)
    assert_sections_clear(4)
    sleep(delay/2)
    trigger_signals_passed(2)
    sleep(delay)
    set_signals_on(13)
    sleep(delay)
    set_subsidaries_off(2)
    sleep(delay)
    trigger_signals_passed(2)
    assert_sections_occupied(4)
    assert_sections_clear(12)
    sleep(delay/2)
    trigger_signals_passed(13)
    sleep(delay)
    set_subsidaries_on(2)
    sleep(delay)
    # Revert the points to normal
    set_fpls_off(3)
    set_points_normal(3)
    set_fpls_on(3)
    sleep(delay)
    # Finally clear the track occupancy
    set_sections_clear(4)
    return()

#-----------------------------------------------------------------------------------

def run_all_automation_example_tests(delay:float=0.0):
    initialise_test_harness(filename="../configuration_examples/automation_colour_light_example.sig")
    # Edit/save all schematic objects to give confidence that editing doesn't break the layout configuration
    set_edit_mode()
    test_object_edit_windows.test_all_object_edit_windows(delay)
    set_run_mode()
    reset_layout()
    run_initial_state_tests()
    run_colour_light_aspect_tests()
    test_interlocking_examples.run_signal_route_tests()
    test_interlocking_examples.run_point_interlocking_tests()
    test_interlocking_examples.run_signal_interlocking_tests()
    run_signal_override_tests()
    run_main_line_tests_1(delay)
    run_main_line_tests_2(delay)
    run_loop_line_tests(delay)
    run_shunting_tests(delay)
    initialise_test_harness(filename="../configuration_examples/automation_semaphore_example.sig")
    # Edit/save all schematic objects to give confidence that editing doesn't break the layout configuration
    set_edit_mode()
    test_object_edit_windows.test_all_object_edit_windows(delay)
    set_run_mode()
    reset_layout()
    run_initial_state_tests(semaphore=True)
    run_semaphore_aspect_tests()
    test_interlocking_examples.run_signal_route_tests()
    test_interlocking_examples.run_point_interlocking_tests()
    test_interlocking_examples.run_signal_interlocking_tests()
    run_signal_override_tests()
    run_semaphore_override_ahead_tests()
    run_main_line_tests_1(delay)
    run_main_line_tests_2(delay)
    run_loop_line_tests(delay)
    run_shunting_tests(delay)
    run_main_line_approach_control_tests(delay)
    run_loop_line_approach_control_tests(delay)
    report_results()
    
if __name__ == "__main__":
    start_application(lambda:run_all_automation_example_tests(delay=0.0))

######################################################################################################

