from system_test_harness import *

initialise_test_harness(filename="../configuration_examples/approach_control_colour_light_example.sig")
sleep(1)
print("Test 1a")
set_signals_off(1)
assert_points_locked(2)
assert_signals_locked(15,13)
sleep(1)
print("Test 2a")
set_signals_on(1)
assert_points_unlocked(2)
assert_signals_unlocked(15,13)
sleep(1)
print("Test 3a")
set_fpl_off(2)
assert_signals_locked(1,6,5,15)
sleep(1)
print("Test 3b")
set_points_switched(2)
sleep(1)
set_fpl_on(2)
assert_signals_locked(5,15)
assert_signals_unlocked(1,6)
sleep(1)
print("Test 4a")
set_signals_off(1)
assert_signals_locked(6)
sleep(0.5)
complete_tests()
