#-----------------------------------------------------------------------------------
# System tests for the schematic editor functions
#-----------------------------------------------------------------------------------

from system_test_harness import *

#-----------------------------------------------------------------------------------

def run_basic_editor_tests(delay:float=0.0):
    # Add elements to the layout and move them to their initial positions
    s1 = create_colour_light_signal()
    sleep(delay)
    select_and_move_objects(s1,100,100,delay=delay)
    sleep(delay)
    s2 = create_semaphore_signal()
    sleep(delay)
    select_and_move_objects(s2,250,100,delay=delay)
    sleep(delay)
    s3 = create_ground_position_signal()
    sleep(delay)
    select_and_move_objects(s3,400,100,delay=delay)
    sleep(delay)
    s4 = create_ground_disc_signal()
    sleep(delay)
    select_and_move_objects(s4,500,100,delay=delay)
    sleep(delay)
    p1 = create_left_hand_point()
    sleep(delay)
    select_and_move_objects(p1,575,100,delay=delay)
    sleep(delay)
    p2 = create_right_hand_point()
    sleep(delay)
    select_and_move_objects(p2,625,100,delay=delay)
    sleep(delay)
    t1 = create_track_section()
    sleep(delay)
    select_and_move_objects(t1,700,100,delay=delay)
    sleep(delay)
    i1 = create_block_instrument()
    sleep(delay)
    select_and_move_objects(i1,200,300,delay=delay)
    sleep(delay)
    l1 = create_line()
    sleep(delay)
    select_and_move_objects(l1,200,150,delay=delay)
    sleep(delay)
    l2 = create_line()
    select_and_move_objects(l2,500,150,delay=delay)
    sleep(delay)
    # Line2 will remain selected after the move
    deselect_all_objects()
    sleep(delay)
    # Test initial moves have been successful
    assert_object_position(s1,100,100)
    assert_object_position(s2,250,100)
    assert_object_position(s3,400,100)
    assert_object_position(s4,500,100)
    assert_object_position(p1,575,100)
    assert_object_position(p2,625,100)
    assert_object_position(t1,700,100)
    assert_object_position(i1,200,300)
    assert_object_position(l1,175,150,225,150)
    assert_object_position(l2,475,150,525,150)
    # Object selection tests (Left Click)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    select_single_object(s1)
    sleep(delay)
    assert_objects_selected(s1)
    assert_objects_deselected(s2,s3,s4,p1,p2,t1,l1,l2,i1)
    select_single_object(s2)
    sleep(delay)
    assert_objects_selected(s2)
    assert_objects_deselected(s1,s3,s4,p1,p2,t1,l1,l2,i1)
    select_single_object(s3)
    sleep(delay)
    assert_objects_selected(s3)
    assert_objects_deselected(s1,s2,s4,p1,p2,t1,l1,l2,i1)
    select_single_object(s4)
    sleep(delay)
    assert_objects_selected(s4)
    assert_objects_deselected(s1,s2,s3,p1,p2,t1,l1,l2,i1)
    select_single_object(p1)
    sleep(delay)
    assert_objects_selected(p1)
    assert_objects_deselected(s1,s2,s3,s4,p2,t1,l1,l2,i1)
    select_single_object(p2)
    sleep(delay)
    assert_objects_selected(p2)
    assert_objects_deselected(s1,s2,s3,s4,p1,t1,l1,l2,i1)
    select_single_object(t1)
    sleep(delay)
    assert_objects_selected(t1)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,l1,l2,i1)
    select_single_object(l1)
    sleep(delay)
    assert_objects_selected(l1)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l2,i1)
    select_single_object(l2)
    sleep(delay)
    assert_objects_selected(l2)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,i1)
    # Object selection tests (Left ShiftClick)
    assert_objects_selected(l2)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,i1)
    select_or_deselect_objects(l1)
    sleep(delay)
    assert_objects_selected(l1,l2)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,i1)
    select_or_deselect_objects(s1)
    sleep(delay)
    assert_objects_selected(l1,l2,s1)
    assert_objects_deselected(s2,s3,s4,p1,p2,t1,i1)
    select_or_deselect_objects(s2)
    sleep(delay)
    assert_objects_selected(l1,l2,s1,s2)
    assert_objects_deselected(s3,s4,p1,p2,t1,i1)
    select_or_deselect_objects(s3)
    sleep(delay)
    assert_objects_selected(l1,l2,s1,s2,s3)
    assert_objects_deselected(s4,p1,p2,t1,i1)
    select_or_deselect_objects(s4)
    sleep(delay)
    assert_objects_selected(l1,l2,s1,s2,s3,s4)
    assert_objects_deselected(p1,p2,t1,i1)
    select_or_deselect_objects(p1)
    sleep(delay)
    assert_objects_selected(l1,l2,s1,s2,s3,s4,p1)
    assert_objects_deselected(p2,t1,i1)
    select_or_deselect_objects(p2)
    sleep(delay)
    assert_objects_selected(l1,l2,s1,s2,s3,s4,p1,p2)
    assert_objects_deselected(t1,i1)
    select_or_deselect_objects(t1)
    sleep(delay)
    assert_objects_selected(l1,l2,s1,s2,s3,s4,p1,p2,t1)
    assert_objects_deselected(i1)
    select_or_deselect_objects(i1)
    sleep(delay)
    assert_objects_selected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    # Object de-selection tests (Left ShiftClick)
    assert_objects_selected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    select_or_deselect_objects(s1)
    sleep(delay)
    assert_objects_selected(s2,s3,s4,p1,p2,t1,l1,l2,i1)
    assert_objects_deselected(s1)
    select_or_deselect_objects(s2)
    sleep(delay)
    assert_objects_selected(s3,s4,p1,p2,t1,l1,l2,i1)
    assert_objects_deselected(s1,s2)
    select_or_deselect_objects(s3)
    sleep(delay)
    assert_objects_selected(s4,p1,p2,t1,l1,l2,i1)
    assert_objects_deselected(s1,s2,s3)
    select_or_deselect_objects(s4)
    sleep(delay)
    assert_objects_selected(p1,p2,t1,l1,l2,i1)
    assert_objects_deselected(s1,s2,s3,s4)
    select_or_deselect_objects(p1)
    sleep(delay)
    assert_objects_selected(p2,t1,l1,l2,i1)
    assert_objects_deselected(s1,s2,s3,s4,p1)
    select_or_deselect_objects(p2)
    sleep(delay)
    assert_objects_selected(t1,l1,l2,i1)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2)
    select_or_deselect_objects(t1)
    sleep(delay)
    assert_objects_selected(l1,l2,i1)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1)
    select_or_deselect_objects(l1)
    sleep(delay)
    assert_objects_selected(l2,i1)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1)
    select_or_deselect_objects(l2)
    sleep(delay)
    assert_objects_selected(i1)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2)
    select_or_deselect_objects(i1)
    sleep(delay)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    # Test editing of line ends
    select_single_object(l1)
    sleep(delay)
    select_and_move_line_end(l1,1,25,100,delay=delay)
    sleep(delay)
    select_and_move_line_end(l1,2,550,100,delay=delay)
    sleep(delay)
    select_single_object(l2)
    sleep(delay)
    select_and_move_line_end(l2,1,650,100,delay=delay)
    sleep(delay)
    select_and_move_line_end(l2,2,800,100,delay=delay)
    sleep(delay)
    assert_object_position(l1,25,100,550,100)
    assert_object_position(l2,650,100,800,100)
    # Test area selection
    select_area(10,10,850,200,delay=delay)
    sleep(delay)
    assert_objects_selected(s1,s2,s3,s4,p1,p2,t1,l1,l2)
    assert_objects_deselected(i1)
    select_and_move_objects(s3,450,150,delay=delay) 
    sleep(delay)
    assert_object_position(s1,150,150)
    assert_object_position(s2,300,150)
    assert_object_position(s3,450,150)
    assert_object_position(s4,550,150)
    assert_object_position(p1,625,150)
    assert_object_position(p2,675,150)
    assert_object_position(t1,750,150)
    assert_object_position(l1,75,150,600,150)
    assert_object_position(l2,700,150,850,150)
    assert_objects_selected(s1,s2,s3,s4,p1,p2,t1,l1,l2)
    assert_objects_deselected(i1)
    deselect_all_objects()    
    sleep(delay)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2)
    # Test select all objects & Rotate of signals & Points
    select_all_objects()    
    sleep(delay)
    assert_objects_selected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    assert_object_configuration(s1,{"orientation" : 0})
    assert_object_configuration(s2,{"orientation" : 0})
    assert_object_configuration(s3,{"orientation" : 0})
    assert_object_configuration(s4,{"orientation" : 0})
    assert_object_configuration(p1,{"orientation" : 0})
    assert_object_configuration(p2,{"orientation" : 0})
    rotate_selected_objects()
    sleep(delay)
    assert_object_configuration(s1,{"orientation" : 180})
    assert_object_configuration(s2,{"orientation" : 180})
    assert_object_configuration(s3,{"orientation" : 180})
    assert_object_configuration(s4,{"orientation" : 180})
    assert_object_configuration(p1,{"orientation" : 180})
    assert_object_configuration(p2,{"orientation" : 180})
    # Test copy and paste and then move(not the block instrument)
    select_or_deselect_objects(i1)
    sleep(delay)
    assert_objects_selected(s1,s2,s3,s4,p1,p2,t1,l1,l2)
    assert_objects_deselected(i1)
    copy_selected_objects()
    sleep(delay)
    new_objects = paste_clipboard_objects()
    [s11,s12,s13,s14,p11,p12,t11,l11,l12] = new_objects
    sleep(delay)
    assert_objects_selected(s11,s12,s13,s14,p11,p12,t11,l11,l12)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    # Select the Track section (should not be overlayed)
    select_and_move_objects(t11,750,75,delay=delay)
    sleep(1)
    # Test delete of selected objects
    assert_objects_selected(s11,s12,s13,s14,p11,p12,t11,l11,l12)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    delete_selected_objects()
    sleep(delay)
    assert_objects_do_not_exist(s11,s12,s13,s14,p11,p12,t11,l11,l12)
    assert_objects_exists(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    # Finally test copy/paste of block instrument
    select_single_object(i1)
    sleep(delay)
    assert_objects_selected(i1)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2)
    copy_selected_objects()
    sleep(delay)
    new_objects = paste_clipboard_objects()
    [i11] = new_objects
    assert_objects_selected(i11)
    assert_objects_deselected(s1,s2,s3,s4,p1,p2,t1,l1,l2,i1)
    sleep(delay)
    # Select and move the original instrument (as this will get selected if we try to select the new one)
    select_and_move_objects(i1,600,325,delay=delay)
    assert_object_position(i1,600,325)
    return()

######################################################################################################

def run_all_schematic_editor_tests(delay=0):
    initialise_test_harness()
    set_edit_mode()
    run_basic_editor_tests(delay)

if __name__ == "__main__":
    run_all_schematic_editor_tests(delay = 0.1)
    complete_tests(shutdown=False)

###############################################################################################################################
    
